# Generated by Django 3.1.1 on 2020-10-14 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
            ],
            options={
                'db_table': 'currentUser',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('dateRegistered', models.DateField(default=datetime.datetime.now)),
                ('SKU', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('genericName', models.CharField(max_length=100)),
                ('commonBrand', models.CharField(max_length=100)),
                ('manufacturedDate', models.DateField(default=datetime.datetime.now)),
                ('expiryDate', models.DateField(default=datetime.datetime.now)),
                ('size', models.IntegerField()),
                ('howToUse', models.TextField()),
                ('sideEffects', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noOfItems', models.IntegerField()),
                ('images', models.ImageField(upload_to='upload/')),
                ('isDeleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('birthPlace', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('spouseName', models.CharField(max_length=50)),
                ('spouseOccupation', models.CharField(max_length=20)),
                ('children', models.IntegerField(default=0)),
                ('motherName', models.CharField(max_length=50)),
                ('motherOccupation', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherOccupation', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('religion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='abcpharma.person')),
                ('photo', models.FileField(upload_to='')),
                ('dateRegistered', models.DateField(default=datetime.datetime(2020, 10, 14, 15, 15, 51, 425031))),
                ('isDeleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('abcpharma.person',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedDate', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicine', to='abcpharma.medicine')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='abcpharma.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
