# Generated by Django 3.1.1 on 2020-10-10 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateRegistered',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 20, 0, 49, 702141)),
        ),
    ]
