# Generated by Django 3.1.1 on 2020-10-10 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpharma', '0002_auto_20201010_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateRegistered',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 21, 2, 41, 951447)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderedDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
